[package]
name        = "dev.peios.libpeios-devel"
description = "Peios userspace C ABI library development files"



[dependencies]
"dev.peios.libpeios" = "= {{release}}"
# Public libpeios headers include the Peios kernel UAPI under <pkm/*.h>.
"dev.peios.kernel-headers" = ">= 0.20.1-rc13-1"

[files]
"@source:LICENSE"                                = "usr/share/licenses/dev.peios.libpeios-devel/LICENSE"
":usr/include/**"                                = "usr/include"
":usr/lib/x86_64-linux-peios/libpeios.so"        = "usr/lib/x86_64-linux-peios/libpeios.so"
":usr/lib/x86_64-linux-peios/pkgconfig/peios.pc" = "usr/lib/x86_64-linux-peios/pkgconfig/peios.pc"
