[package]
name        = "dev.peios.libpeios-static"
description = "Peios userspace C ABI library static archive"



[dependencies]
"dev.peios.libpeios-devel" = "= {{release}}"

[files]
"@source:LICENSE"                        = "usr/share/licenses/dev.peios.libpeios-static/LICENSE"
":usr/lib/x86_64-linux-peios/libpeios.a" = "usr/lib/x86_64-linux-peios/libpeios.a"
