[package]
name         = "dev.peios.libpeios-debugsource"
architecture = "noarch"
description  = "Peios userspace C ABI library debug sources"



[dependencies]
"dev.peios.libpeios-debuginfo" = "= {{release}}"

[files]
"@source:LICENSE"       = "usr/share/licenses/dev.peios.libpeios-debugsource/LICENSE"
":licenses/**"          = "usr/share/licenses/dev.peios.libpeios-debugsource/third-party"
":usr/src/debug/**"     = "usr/src/debug"
