[package]
name        = "dev.peios.libpeios-debuginfo"
description = "Peios userspace C ABI library debugging symbols"



[dependencies]
"dev.peios.libpeios" = "= {{release}}"

[files]
"@source:LICENSE"   = "usr/share/licenses/dev.peios.libpeios-debuginfo/LICENSE"
":usr/lib/debug/**" = "usr/lib/debug"
