/* @generated by cbindgen from the Rust source — do not edit. */

#ifndef PEIOS_ABI_GENERATED_H
#define PEIOS_ABI_GENERATED_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <sys/types.h>
#include <pkm/pkm.h>
#include <pkm/kmes.h>
#include <pkm/lcs.h>

struct peios_acl_builder;

struct peios_event_reader;

struct peios_mp_writer;

struct peios_sd_builder;

struct peios_token_builder;

struct peios_access_request {
  int token_fd;
  const void *sd;
  size_t sd_len;
  uint32_t desired;
  struct kacs_generic_mapping mapping;
  const void *self_sid;
  size_t self_sid_len;
  uint32_t privilege_intent;
  const struct kacs_object_type_entry *object_tree;
  uint32_t object_tree_count;
  const void *local_claims;
  size_t local_claims_len;
  uint32_t pip_type;
  uint32_t pip_trust;
  const void *audit_context;
  size_t audit_context_len;
};

struct peios_access_audit {
  uint32_t continuous_audit;
  int staging_mismatch;
};

struct peios_ace_view {
  uint64_t _opaque[4];
};

struct peios_ace_spec {
  uint8_t type_;
  uint8_t flags;
  uint32_t mask;
  const void *sid;
  size_t sid_len;
  const uint8_t *object_type;
  const uint8_t *inherited_object_type;
  const void *app_data;
  size_t app_data_len;
};

struct peios_acl_view {
  uint64_t _opaque[4];
};

struct peios_event_entry {
  const char *event_type;
  uint16_t event_type_len;
  const void *payload;
  uint32_t payload_len;
};

struct peios_event {
  uint64_t timestamp;
  uint64_t sequence;
  uint16_t cpu_id;
  uint8_t origin_class;
  uint8_t effective_token_guid[16];
  uint8_t true_token_guid[16];
  uint8_t process_guid[16];
  const char *event_type;
  uint16_t event_type_len;
  const void *payload;
  uint32_t payload_len;
};

struct peios_event_ring {
  uint64_t _opaque[4];
};

struct peios_open_params {
  uint32_t desired_access;
  uint32_t disposition;
  uint32_t options;
  uint32_t flags;
  const void *sd;
  size_t sd_len;
};

struct peios_mount_policy {
  uint32_t policy;
  uint32_t flags;
  uint32_t generation;
  const void *template_sd;
  size_t template_sd_len;
};

struct peios_mp_reader {
  uint64_t _opaque[4];
};

struct peios_reg_subkey {
  void *name;
  uint64_t last_write_time;
  uint32_t name_cap;
  uint32_t name_len;
  uint32_t subkey_count;
  uint32_t value_count;
};

struct peios_reg_enum_value {
  void *name;
  void *data;
  uint32_t type_;
  uint32_t name_cap;
  uint32_t name_len;
  uint32_t data_cap;
  uint32_t data_len;
};

struct peios_reg_key_info {
  void *name;
  uint64_t last_write_time;
  uint64_t hive_generation;
  uint32_t name_cap;
  uint32_t name_len;
  uint32_t subkey_count;
  uint32_t value_count;
  uint32_t max_subkey_name_len;
  uint32_t max_value_name_len;
  uint32_t max_value_data_size;
  uint32_t sd_size;
  uint8_t volatile_key;
  uint8_t symlink;
};

struct peios_reg_value {
  uint64_t sequence;
  void *data;
  void *layer;
  uint32_t type_;
  uint32_t data_cap;
  uint32_t data_len;
  uint32_t layer_cap;
  uint32_t layer_len;
};

struct peios_sd_view {
  uint64_t _opaque[8];
};

struct peios_session_spec {
  uint8_t logon_type;
  const char *auth_package;
  const void *user_sid;
  size_t user_sid_len;
};

struct peios_sid_array_view {
  uint64_t _opaque[4];
};

struct peios_token_claim_value {
  uint64_t scalar;
  const void *bytes;
  size_t len;
};

struct peios_token_claim {
  const char *name;
  uint16_t value_type;
  uint32_t flags;
  const struct peios_token_claim_value *values;
  unsigned int value_count;
};

struct peios_token_flags {
  bool write_restricted;
  bool user_deny_only;
  bool isolation_boundary;
  bool confinement_exempt;
};

struct peios_token_lcs_credentials {
  const uint8_t (*scope_guids)[16];
  unsigned int scope_count;
  const char *const *private_layers;
  unsigned int private_layer_count;
};

struct peios_privilege_set {
  uint64_t present;
  uint64_t enabled;
  uint64_t enabled_by_default;
  uint64_t used;
};

struct peios_token_restrict {
  uint64_t privs_to_delete;
  const uint32_t *deny_group_indices;
  unsigned int deny_count;
  const void *const *restrict_sids;
  const size_t *restrict_sid_lens;
  unsigned int restrict_count;
  uint32_t flags;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const struct kacs_generic_mapping peios_file_generic_mapping;

extern const struct kacs_generic_mapping peios_token_generic_mapping;

int peios_access_check(const struct peios_access_request *req,
                       uint32_t *granted,
                       struct peios_access_audit *audit);

int peios_access_check_list(const struct peios_access_request *req,
                            struct kacs_node_result *results,
                            uint32_t count);

uint32_t peios_access_map_generic(uint32_t mask, const struct kacs_generic_mapping *m);

int peios_ace_view_app_data(const struct peios_ace_view *e, const void **data, size_t *len);

uint8_t peios_ace_view_flags(const struct peios_ace_view *e);

int peios_ace_view_inherited_object_type(const struct peios_ace_view *e, const uint8_t **guid16);

uint32_t peios_ace_view_mask(const struct peios_ace_view *e);

int peios_ace_view_object_type(const struct peios_ace_view *e, const uint8_t **guid16);

int peios_ace_view_sid(const struct peios_ace_view *e, const void **sid, size_t *len);

uint8_t peios_ace_view_type(const struct peios_ace_view *e);

void peios_acl_builder_add(struct peios_acl_builder *b, const struct peios_ace_spec *ace);

void peios_acl_builder_allow(struct peios_acl_builder *b,
                             const void *sid,
                             size_t len,
                             uint32_t mask,
                             uint8_t flags);

void peios_acl_builder_audit(struct peios_acl_builder *b,
                             const void *sid,
                             size_t len,
                             uint32_t mask,
                             uint8_t flags);

const void *peios_acl_builder_bytes(struct peios_acl_builder *b, size_t *len_out);

void peios_acl_builder_deny(struct peios_acl_builder *b,
                            const void *sid,
                            size_t len,
                            uint32_t mask,
                            uint8_t flags);

int peios_acl_builder_error(const struct peios_acl_builder *b);

ptrdiff_t peios_acl_builder_finish(struct peios_acl_builder *b, void *buf, size_t cap);

void peios_acl_builder_free(struct peios_acl_builder *b);

void peios_acl_builder_label(struct peios_acl_builder *b,
                             uint32_t integrity_rid,
                             uint32_t policy_mask);

struct peios_acl_builder *peios_acl_builder_new(void);

void peios_acl_builder_reset(struct peios_acl_builder *b);

int peios_acl_parse(const void *acl, size_t len, struct peios_acl_view *out);

int peios_acl_view_ace(const struct peios_acl_view *a, unsigned int i, struct peios_ace_view *out);

unsigned int peios_acl_view_count(const struct peios_acl_view *a);

int peios_event_attach(uint32_t cpu_id, uint64_t *capacity_out);

int peios_event_emit(const char *event_type,
                     uint16_t event_type_len,
                     const void *payload,
                     uint32_t payload_len);

int peios_event_emit_batch(const struct peios_event_entry *entries,
                           uint32_t count,
                           uint32_t *emitted_out);

void peios_event_reader_close(struct peios_event_reader *reader);

uint64_t peios_event_reader_lost(const struct peios_event_reader *reader);

int peios_event_reader_next(struct peios_event_reader *reader, struct peios_event *out);

struct peios_event_reader *peios_event_reader_open(uint32_t cpu_id);

int peios_event_reader_wait(struct peios_event_reader *reader, int timeout_ms);

uint64_t peios_event_ring_capacity(const struct peios_event_ring *ring);

ptrdiff_t peios_event_ring_event_at(const struct peios_event_ring *ring,
                                    uint64_t read_pos,
                                    struct peios_event *out);

uint64_t peios_event_ring_generation(const struct peios_event_ring *ring);

int peios_event_ring_map(int fd, uint64_t capacity, struct peios_event_ring *ring);

void peios_event_ring_set_need_wake(const struct peios_event_ring *ring, int set);

uint64_t peios_event_ring_tail_pos(const struct peios_event_ring *ring);

void peios_event_ring_unmap(struct peios_event_ring *ring);

int peios_event_ring_wait(const struct peios_event_ring *ring, uint64_t read_pos, int timeout_ms);

uint64_t peios_event_ring_write_pos(const struct peios_event_ring *ring);

ptrdiff_t peios_fd_get_sd(int fd, uint32_t secinfo, void *buf, size_t cap);

int peios_fd_set_sd(int fd, uint32_t secinfo, const void *sd, size_t len);

ptrdiff_t peios_file_get_sd(int dirfd,
                            const char *path,
                            uint32_t secinfo,
                            void *buf,
                            size_t cap,
                            uint32_t at_flags);

int peios_file_open(int dirfd,
                    const char *path,
                    const struct peios_open_params *p,
                    uint32_t *status_out);

int peios_file_set_sd(int dirfd,
                      const char *path,
                      uint32_t secinfo,
                      const void *sd,
                      size_t len,
                      uint32_t at_flags);

int peios_mount_get_policy(int fd, struct peios_mount_policy *out, void *tmpl_buf, size_t tmpl_cap);

int peios_mount_set_policy(int fd, const struct peios_mount_policy *p);

int peios_mp_peek(const struct peios_mp_reader *r);

ptrdiff_t peios_mp_read_array(struct peios_mp_reader *r);

ptrdiff_t peios_mp_read_bin(struct peios_mp_reader *r, const void **out);

int peios_mp_read_bool(struct peios_mp_reader *r, bool *out);

ptrdiff_t peios_mp_read_ext(struct peios_mp_reader *r, int8_t *type_out, const void **out);

int peios_mp_read_float(struct peios_mp_reader *r, double *out);

int peios_mp_read_int(struct peios_mp_reader *r, int64_t *out);

ptrdiff_t peios_mp_read_map(struct peios_mp_reader *r);

int peios_mp_read_nil(struct peios_mp_reader *r);

ptrdiff_t peios_mp_read_str(struct peios_mp_reader *r, const char **out);

int peios_mp_read_uint(struct peios_mp_reader *r, uint64_t *out);

void peios_mp_reader_init(struct peios_mp_reader *r, const void *buf, size_t len);

size_t peios_mp_reader_remaining(const struct peios_mp_reader *r);

int peios_mp_skip(struct peios_mp_reader *r);

int peios_mp_validate(const void *buf, size_t len, uint32_t max_depth);

void peios_mp_write_array(struct peios_mp_writer *w, uint32_t count);

void peios_mp_write_bin(struct peios_mp_writer *w, const void *b, size_t len);

void peios_mp_write_bool(struct peios_mp_writer *w, bool v);

void peios_mp_write_ext(struct peios_mp_writer *w, int8_t ext_type, const void *b, size_t len);

void peios_mp_write_float(struct peios_mp_writer *w, double v);

void peios_mp_write_int(struct peios_mp_writer *w, int64_t v);

void peios_mp_write_map(struct peios_mp_writer *w, uint32_t count);

void peios_mp_write_nil(struct peios_mp_writer *w);

void peios_mp_write_raw(struct peios_mp_writer *w, const void *b, size_t len);

void peios_mp_write_str(struct peios_mp_writer *w, const char *s, size_t len);

void peios_mp_write_uint(struct peios_mp_writer *w, uint64_t v);

ptrdiff_t peios_mp_writer_bytes(struct peios_mp_writer *w, const void **out);

int peios_mp_writer_error(const struct peios_mp_writer *w);

void peios_mp_writer_free(struct peios_mp_writer *w);

struct peios_mp_writer *peios_mp_writer_new(void);

void peios_mp_writer_reset(struct peios_mp_writer *w);

int peios_process_set_mitigations(int pidfd, uint32_t mitigations);

int peios_reg_backup(int key_fd, int output_fd);

int peios_reg_begin_transaction(void);

int peios_reg_blanket_tombstone(int key_fd,
                                const void *layer,
                                uint32_t layer_len,
                                int set,
                                int txn_fd);

int peios_reg_commit(int txn_fd);

int peios_reg_create_key(int parent_fd,
                         const char *path,
                         uint32_t desired_access,
                         uint32_t flags,
                         const char *layer,
                         int txn_fd,
                         uint32_t *disposition_out);

int peios_reg_delete_key(int key_fd, const void *layer, uint32_t layer_len, int txn_fd);

int peios_reg_delete_value(int key_fd,
                           const void *name,
                           uint32_t name_len,
                           const void *layer,
                           uint32_t layer_len,
                           int txn_fd);

int peios_reg_enum_subkey(int key_fd, uint32_t index, int txn_fd, struct peios_reg_subkey *v);

int peios_reg_enum_value(int key_fd, uint32_t index, int txn_fd, struct peios_reg_enum_value *v);

int peios_reg_flush(int key_fd);

int peios_reg_get_security(int key_fd,
                           uint32_t security_info,
                           void *sd,
                           uint32_t cap,
                           uint32_t *sd_len_out);

int peios_reg_hide_key(int key_fd, const void *layer, uint32_t layer_len, int txn_fd);

int peios_reg_notify(int key_fd, uint32_t filter, int subtree);

int peios_reg_open_key(int parent_fd, const char *path, uint32_t desired_access, uint32_t flags);

int peios_reg_query_key_info(int key_fd, struct peios_reg_key_info *v);

int peios_reg_query_value(int key_fd,
                          const void *name,
                          uint32_t name_len,
                          int txn_fd,
                          struct peios_reg_value *v);

int peios_reg_query_values_batch(int key_fd,
                                 int txn_fd,
                                 void *buf,
                                 uint32_t cap,
                                 uint32_t *len_out,
                                 uint32_t *count_out);

int peios_reg_restore(int key_fd, int input_fd);

int peios_reg_set_security(int key_fd,
                           uint32_t security_info,
                           const void *sd,
                           uint32_t sd_len,
                           int txn_fd);

int peios_reg_set_value(int key_fd,
                        const void *name,
                        uint32_t name_len,
                        uint32_t type_,
                        const void *data,
                        uint32_t data_len,
                        const void *layer,
                        uint32_t layer_len,
                        int txn_fd,
                        uint64_t expected_seq);

int peios_reg_txn_status(int txn_fd, uint32_t *state_out, int *terminal_errno_out);

const void *peios_sd_builder_bytes(struct peios_sd_builder *b, size_t *len_out);

void peios_sd_builder_control(struct peios_sd_builder *b, uint16_t set, uint16_t clear);

void peios_sd_builder_dacl(struct peios_sd_builder *b, const void *acl, size_t len);

void peios_sd_builder_dacl_null(struct peios_sd_builder *b);

int peios_sd_builder_error(const struct peios_sd_builder *b);

ptrdiff_t peios_sd_builder_finish(struct peios_sd_builder *b, void *buf, size_t cap);

void peios_sd_builder_free(struct peios_sd_builder *b);

void peios_sd_builder_group(struct peios_sd_builder *b, const void *sid, size_t len);

struct peios_sd_builder *peios_sd_builder_new(void);

void peios_sd_builder_owner(struct peios_sd_builder *b, const void *sid, size_t len);

void peios_sd_builder_reset(struct peios_sd_builder *b);

void peios_sd_builder_sacl(struct peios_sd_builder *b, const void *acl, size_t len);

int peios_sd_parse(const void *sd, size_t len, struct peios_sd_view *out);

ptrdiff_t peios_sd_reinherit(void *out,
                             size_t cap,
                             const void *parent_sd,
                             size_t parent_len,
                             const void *child_sd,
                             size_t child_len,
                             int is_container);

ptrdiff_t peios_sd_strip_inherited(void *out,
                                   size_t cap,
                                   const void *sd,
                                   size_t sd_len,
                                   uint32_t info);

uint16_t peios_sd_view_control(const struct peios_sd_view *v);

int peios_sd_view_dacl(const struct peios_sd_view *v, struct peios_acl_view *out);

int peios_sd_view_group(const struct peios_sd_view *v, const void **sid, size_t *len);

int peios_sd_view_owner(const struct peios_sd_view *v, const void **sid, size_t *len);

int peios_sd_view_sacl(const struct peios_sd_view *v, struct peios_acl_view *out);

ptrdiff_t peios_sddl_format_condition(char *out, size_t cap, const void *artx, size_t len);

ptrdiff_t peios_sddl_format_sd(char *out, size_t cap, const void *sd, size_t sd_len);

ptrdiff_t peios_sddl_parse_condition(void *out, size_t cap, const char *expr);

ptrdiff_t peios_sddl_parse_sd(void *out, size_t cap, const char *sddl);

int peios_session_create(const struct peios_session_spec *spec, uint64_t *id_out);

int peios_session_destroy_empty(uint64_t session_id);

unsigned int peios_sid_array_count(const struct peios_sid_array_view *a);

int peios_sid_array_get(const struct peios_sid_array_view *a,
                        unsigned int i,
                        const void **sid,
                        size_t *len,
                        uint32_t *attrs);

int peios_sid_array_parse(const void *blob, size_t len, struct peios_sid_array_view *out);

ptrdiff_t peios_sid_build(void *out,
                          size_t cap,
                          uint64_t id_authority,
                          const uint32_t *sub_auths,
                          unsigned int count);

bool peios_sid_equal(const void *a, size_t alen, const void *b, size_t blen);

ptrdiff_t peios_sid_format(const void *sid, size_t len, char *out, size_t cap);

ptrdiff_t peios_sid_integrity(void *out, size_t cap, uint32_t level_rid);

size_t peios_sid_length(const void *sid);

ptrdiff_t peios_sid_logon(void *out, size_t cap, uint64_t session_id);

ptrdiff_t peios_sid_parse_string(void *out, size_t cap, const char *sddl);

uint32_t peios_sid_rid(const void *sid, size_t len);

bool peios_sid_valid(const void *sid, size_t len);

ptrdiff_t peios_sid_well_known(void *out, size_t cap, int which);

int peios_token_adjust_default(int fd,
                               const void *dacl,
                               size_t len,
                               uint16_t owner_index,
                               uint16_t group_index);

int peios_token_adjust_groups(int fd,
                              const struct kacs_group_entry *entries,
                              unsigned int count,
                              uint64_t *prev_state);

int peios_token_adjust_privileges(int fd,
                                  const struct kacs_priv_entry *entries,
                                  unsigned int count,
                                  uint64_t *prev_enabled);

void peios_token_builder_add_device_claim(struct peios_token_builder *b,
                                          const struct peios_token_claim *claim);

void peios_token_builder_add_device_group(struct peios_token_builder *b,
                                          const void *sid,
                                          size_t len,
                                          uint32_t attrs);

void peios_token_builder_add_group(struct peios_token_builder *b,
                                   const void *sid,
                                   size_t len,
                                   uint32_t attrs);

void peios_token_builder_add_restricted_sid(struct peios_token_builder *b,
                                            const void *sid,
                                            size_t len,
                                            uint32_t attrs);

void peios_token_builder_add_user_claim(struct peios_token_builder *b,
                                        const struct peios_token_claim *claim);

void peios_token_builder_audit_policy(struct peios_token_builder *b, uint32_t bits);

ptrdiff_t peios_token_builder_bytes(struct peios_token_builder *b, const void **out);

void peios_token_builder_confinement(struct peios_token_builder *b, const void *sid, size_t len);

int peios_token_builder_create(struct peios_token_builder *b);

void peios_token_builder_default_dacl(struct peios_token_builder *b, const void *acl, size_t len);

int peios_token_builder_error(const struct peios_token_builder *b);

void peios_token_builder_expiration(struct peios_token_builder *b, uint64_t when);

void peios_token_builder_flags(struct peios_token_builder *b, const struct peios_token_flags *f);

void peios_token_builder_free(struct peios_token_builder *b);

void peios_token_builder_integrity(struct peios_token_builder *b, uint32_t rid);

void peios_token_builder_lcs_credentials(struct peios_token_builder *b,
                                         const struct peios_token_lcs_credentials *creds);

void peios_token_builder_mandatory_policy(struct peios_token_builder *b, uint32_t bits);

struct peios_token_builder *peios_token_builder_new(void);

void peios_token_builder_owner_index(struct peios_token_builder *b, uint32_t index);

void peios_token_builder_primary_group_index(struct peios_token_builder *b, uint32_t index);

void peios_token_builder_privileges(struct peios_token_builder *b,
                                    uint64_t present,
                                    uint64_t enabled);

void peios_token_builder_projected_ids(struct peios_token_builder *b, uint32_t uid, uint32_t gid);

void peios_token_builder_reset(struct peios_token_builder *b);

void peios_token_builder_session(struct peios_token_builder *b, uint64_t session_id);

void peios_token_builder_source(struct peios_token_builder *b,
                                const char *name,
                                uint64_t source_id);

void peios_token_builder_supp_gids(struct peios_token_builder *b,
                                   const uint32_t *gids,
                                   unsigned int count);

void peios_token_builder_type(struct peios_token_builder *b, uint8_t token_type, uint8_t imp_level);

void peios_token_builder_user(struct peios_token_builder *b, const void *sid, size_t len);

int peios_token_create_raw(const void *spec, size_t len);

int peios_token_duplicate(int fd, uint32_t access, uint8_t token_type, uint8_t imp_level);

int peios_token_get_linked(int fd);

int peios_token_impersonate(int fd);

int peios_token_install(int fd);

int peios_token_integrity(int fd, uint32_t *level_rid_out);

int peios_token_link(int elevated_fd, int filtered_fd, uint64_t session_id);

int peios_token_open_peer(int conn_fd);

int peios_token_open_process(int pidfd, uint32_t access);

int peios_token_open_self(unsigned int flags, uint32_t access);

int peios_token_open_thread(int pidfd, int tid, uint32_t access);

int peios_token_privileges(int fd, struct peios_privilege_set *out);

ptrdiff_t peios_token_query(int fd, uint32_t info_class, void *buf, size_t cap);

int peios_token_reset_groups(int fd);

int peios_token_reset_privileges(int fd);

int peios_token_restrict(int fd, const struct peios_token_restrict *spec);

int peios_token_revert(void);

int peios_token_session_id(int fd, uint32_t *out);

int peios_token_set_session_id(int fd, uint32_t session_id);

int peios_token_type(int fd, uint32_t *out);

ptrdiff_t peios_token_user(int fd, void *sid_buf, size_t cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PEIOS_ABI_GENERATED_H */
